version: latest

services:
  postgres:  
    image: postgres:latest  
    container_name: postgresDb  
    env_file: 
      - ./Database/env/environments.env
    ports:
      - "5432:5432"  
    volumes:
      - ./Database/data:/var/lib/postgresql/data  

