GRANT SPARQL_UPDATE TO "SPARQL";
GRANT EXECUTE ON DB.DBA.SPARQL_INSERT_DICT_CONTENT TO "SPARQL";
GRANT EXECUTE ON DB.DBA.SPARQL_INSERT_DICT TO "SPARQL";

GRANT EXECUTE ON DB.DBA.SPARQL_INSERT TO "SPARQL";

SPARQL CREATE SILENT GRAPH <http://example.org/kst>;
DB.DBA.RDF_GRAPH_USER_PERMS_SET('http://example.org/kst', 'SPARQL', 7);